pred_age=int(input("Enter the age"))
if(pred_age>0 & pred_age<=10):
    print("Food Recommendations:")
    print("fruits, vegetables, whole grains, and proteins.")
    print("Exercise Recommendations:")
    print( "Running, playground activities,Jumping rope, playing basketball")
    print("Books Recommendations:")
    print(" Goodnight Moon by Margaret Wise Brown, The Very Hungry Caterpillar by Eric Carle")
    print("Music Recommendations:")
    print("Twinkle Twinkle Little Star,The Wheels on the Bus,Baby Shark")
elif(pred_age>=11 & pred_age<=20):
    print("Food Recomendations")
    print("Lean meats, beans, nuts,fruits, vegetables, and whole grains")
    print("Exercise Recommendations:")
    print("Running, swimming, cycling,Weight lifting, resistance exercises,soccer, basketball")
    print("Books Recommendations:")
    print("Harry Potter series by J.K. Rowling, The Hunger Games by Suzanne Collins.")
    print("Music Recommendations:")
    print("The Beatles, Queen,Imagine Dragons")
elif(pred_age>=21 & pred_age<=30):
    print("Food Recommendations: ")
    print("Lean meats, eggs, legumes,Avocados, nuts, olive oil,Include a variety of foods from all food groups")
    print("Exercise Recommendations: ")
    print("Stretching exercises, yoga,swimming, cycling, Lifting weights")
    print("Books Recommendations: ")
    print("The Night Circus by Erin Morgenstern, Normal People by Sally Rooney")
    print("Music Recommendations: ")
    print("Taylor Swift, Ed Sheeran, Hozier")
elif(pred_age>=31 & pred_age<=40):
    print("Food Recommendations: ")
    print("Lean meats, eggs, legumes, Avocados, nuts, olive oil,Include a variety of foods from all food groups")
    print("Exercise Recommendations: ")
    print(" Lifting weights, yoga,swimming, cycling, Stretching exercises, yoga")
    print("Books Recommendations: ")
    print("Big Little Lies by Liane Moriarty, The Goldfinch by Donna Tartt")
    print("Music Recommendations: ")
    print("Coldplay, Radiohead")
elif(pred_age>=41 & pred_age<=50):
    print("Food Recommendations: ")
    print(" eggs, legumes,Avocados, nuts,olive oil,Lean meats")
    print("Exercise Recommendations: ")
    print("Lifting weights, yoga,Stretching exercises,walking, swimming, cycling")
    print("Books Recommendations: ")
    print("The Nightingale by Kristin Hannah, The Girl on the Train by Paula Hawkins")
    print("Music Recommendations: ")
    print("U2, Madonna,Maroon 5, P!nk")
elif(pred_age>=51 & pred_age<=60):
    print("Food Recommendations: ")
    print("Include a variety of foods from all food groups,Avocados, nuts, olive oil,Lean meats, eggs, legumes")
    print("Exercise Recommendations: ")
    print(" yoga,Stretching exercises, Lifting weights, yoga,walking, swimming, cycling")
    print("Books Recommendations: ")
    print("The Help by Kathryn Stockett, Where the Crawdads Sing by Delia Owens")
    print("Music Recommendations: ")
    print("Fleetwood Mac, Bruce Springsteen,Adele, Ed Sheeran")
elif(pred_age>=61 & pred_age<=70):
    print("Food Recommendations: ")
    print(" Focus on nutrient-dense foods to meet nutritional needs without excess calories,Whole grains, fruits, vegetables for digestive health,Lean meats, dairy, and legumes to maintain muscle mass")
    print("Exercise Recommendations: ")
    print("Aim for at least 150 minutes of moderate-intensity aerobic activity,Walking, swimming, dancing,Twice a week, using light weights or resistance bands, Balance exercises, yoga, tai chi to prevent falls")
    print("Books Recommendations:")
    print("A Man Called Ove by Fredrik Backman, The Night Circus by Erin Morgenstern")
    print("Music Recommendations:")
    print("The Beatles, Elvis Presley,Miles Davis, Ella Fitzgerald")
elif(pred_age>=71 & pred_age<=80):
    print("Food Recommendations:")
    print("legumes to maintain muscle mass,Lean meats, dairy,Whole grains, fruits, vegetables for digestive health")
    print("Exercise Recommendations: ")
    print("Balance exercises, yoga,Twice a week, using light weights,Walking, swimming, dancing")
    print("Books Recommendations:")
    print("The Unlikely Pilgrimage of Harold Fry by Rachel Joyce")
    print("Music Recommendations: ")
    print("Beethoven, Mozart,Frank Sinatra, Tony Bennett")